version: '3.7'

networks:
  monitor:
    driver: bridge

services:

  db:
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_DATABASE: monitordb
    ports:
      - "3306:3306"
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    hostname: mysql-exporter
    restart: always
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: root:123456@(139.198.186.81:3306)
    networks:
      - monitor

